services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.1
    ports:
      - "5000:5000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    command: >
      mlflow server 
      --backend-store-uri sqlite:///mlflow.db 
      --host 0.0.0.0 
      --port 5000
    volumes:
      - ./mlruns:/mlruns

  credit-risk-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000  # <- TALK TO mlflow container, not localhost
